using SharedKernel.SharedObjects.Paginations;
using SharedKernel.SharedObjects;
using Application.DTOs.Produtos.Filtro;
using Domain.Commands.Produtos.Adicionar;
using Application.DTOs.Produtos.Atualizar;
using Domain.Commands.Produtos.Atualizar;
using Application.DTOs.Pessoas.Filtro;
using Application.DTOs.Produto.Adicionar;
using Domain.Commands.Produtos.Grupos.Adicionar;
using Domain.Commands.Produtos.Grupos.Atualizar;
using Application.DTOs.Produtos.Grupos.Adicionar;
using Application.DTOs.Produtos.Grupos.Atualizar;
using Application.DTOs.Produtos.CodigosImportacoes.Adicionar;
using Application.DTOs.Produtos.CodigosImportacoes.Atualizar;
using Domain.Commands.Produtos.CodigosImportacoes.Atualizar;
using Domain.Commands.Produtos.CodigosImportacoes.Adicionar;
using Domain.Commands.Produtos.Setores.Adicionar;
using Application.DTOs.Produtos.Setores.Adicionar;
using Application.DTOs.Produtos.Setores.Atualizar;
using Domain.Commands.Produtos.Setores.Atualizar;
using Application.DTOs.Produtos.Ruas.Adicionar;
using Application.DTOs.Produtos.Ruas.Atualizar;
using Domain.Commands.Produtos.Ruas.Adicionar;
using Domain.Commands.Produtos.Ruas.Atualizar;
using Application.DTOs.Produtos.Subgrupos.Adicionar;
using Application.DTOs.Produtos.Subgrupos.Atualizar;
using Domain.Commands.Produtos.Subgrupos.Adicionar;
using Domain.Commands.Produtos.Subgrupos.Atualizar;
using Application.DTOs.Produtos.Prateleiras.Adicionar;
using Application.DTOs.Produtos.Prateleiras.Atualizar;
using Domain.Commands.Produtos.Prateleiras.Adicionar;
using Domain.Commands.Produtos.Prateleiras.Atualizar;
using Application.DTOs.Produtos.Ncms.Adicionar;
using Application.DTOs.Produtos.Ncms.Atualizar;
using Application.DTOs.Produtos.Ncms.Filtro;
using Domain.Commands.Produtos.Ncms.Adicionar;
using Domain.Commands.Produtos.Ncms.Atualizar;
using Application.DTOs.Produtos.Familias.Adicionar;
using Application.DTOs.Produtos.Familias.Atualizar;
using Domain.Commands.Produtos.Familias.Adicionar;
using Domain.Commands.Produtos.Familias.Atualizar;
using Domain.Commands.Produtos.TiposProdutos.Adicionar;
using Domain.Commands.Produtos.TiposProdutos.Atualizar;
using Application.DTOs.Produtos.TiposProdutos.Adicionar;
using Application.DTOs.Produtos.TiposProdutos.Atualizar;
using Application.DTOs.Produtos.TiposPrecos.Adicionar;
using Application.DTOs.Produtos.TiposPrecos.Atualizar;
using Domain.Commands.Produtos.TiposPrecos.Atualizar;
using Domain.Commands.Produtos.TiposPrecos.Adicionar;
using Application.DTOs.Produtos.SetoresDeProdutos.Adicionar;
using Application.DTOs.Produtos.SetoresDeProdutos.Atualizar;
using Domain.Commands.Produtos.SetoresProdutos.Atualizar;
using Domain.Commands.Produtos.SetoresProdutos.Adicionar;
using Application.DTOs.Produtos.OrigemMateriais.Adicionar;
using Application.DTOs.Produtos.OrigemMateriais.Atualizar;
using Domain.Commands.Produtos.OrigemMateriais.Adicionar;
using Application.DTOs.Produtos.SetorProduto.Filtro;
using Domain.Commands.Produtos.Excluir;
using Application.DTOs.Produto.Excluir;
using Application.DTOs.Produtos.Grupos.Excluir;
using Domain.Commands.Produtos.Grupos.Excluir;
using Domain.Commands.Produtos.CodigosImportacoes.Excluir;
using Application.DTOs.Produtos.CodigosImportacoes.Excluir;
using Domain.Commands.Produtos.TiposProdutos.Excluir;
using Application.DTOs.Produtos.TiposProdutos.Excluir;
using Application.DTOs.Produtos.Setores.Excluir;
using Domain.Commands.Produtos.Setores.Excluir;
using Application.DTOs.Produtos.Ruas.Excluir;
using Domain.Commands.Produtos.Ruas.Excluir;
using Application.DTOs.Produtos.Subgrupos.Excluir;
using Domain.Commands.Produtos.Subgrupos.Excluir;
using Application.DTOs.Produtos.Prateleiras.Excluir;
using Domain.Commands.Produtos.Prateleiras.Excluir;
using Application.DTOs.Produtos.Ncms.Excluir;
using Domain.Commands.Produtos.Ncms.Excluir;
using Application.DTOs.Produtos.Familias.Excluir;
using Domain.Commands.Produtos.Familias.Excluir;
using Domain.Commands.Produtos.TiposPrecos.Excluir;
using Application.DTOs.Produtos.TiposPrecos.Excluir;
using Domain.Commands.Produtos.SetoresProdutos.Excluir;
using Application.DTOs.Produtos.SetoresDeProdutos.Excluir;
using Domain.Commands.Produtos.OrigemMateriais.Excluir;
using Application.DTOs.Produtos.OrigemMateriais.Excluir;
using Application.DTOs.Produtos.UnidadesMedidas.Adicionar;
using Application.DTOs.Produtos.UnidadesMedidas.Atualizar;
using Application.DTOs.Produtos.UnidadesMedidas.Excluir;
using Application.DTOs.Produtos.UnidadesMedidas.Filtro;
using Domain.Commands.Produtos.UnidadesMedidas.Excluir;
using Domain.Commands.Produtos.UnidadesMedidas.Atualizar;
using Domain.Commands.Produtos.UnidadesMedidas.Adicionar;
using Application.DTOs.Produtos.ClasseReajustes.Adicionar;
using Application.DTOs.Produtos.ClasseReajustes.Atualizar;
using Application.DTOs.Produtos.ClasseReajustes.Excluir;
using Application.DTOs.Produtos.DesgastePolimentos.Adicionar;
using Application.DTOs.Produtos.DesgastePolimentos.Atualizar;
using Application.DTOs.Produtos.DesgastePolimentos.Excluir;
using Domain.Commands.Produtos.ClasseReajustes.Adicionar;
using Domain.Commands.Produtos.DesgastePolimentos.Adicionar;
using Domain.Commands.Produtos.ClasseReajustes.Atualizar;
using Domain.Commands.Produtos.AtualizarDesgastes.Atualizar;
using Domain.Commands.Produtos.DesgastePolimentos.Excluir;
using Domain.Commands.Produtos.ClasseReajustes.Excluir;
using Application.DTOs.Produtos.ClasseReajustes.Filtro;
using Application.DTOs.Produtos.DesgastePolimentos.Filtro;
using Application.DTOs.Produtos;
using Application.DTOs.Produtos.SetoresDeProdutos.Filtro;

namespace Application.Interfaces.Produtos
{
    public interface IProdutoService
    {
        Task<FormularioResponse<AdicionarProdutoCommand>> Adicionar(AdicionarProdutoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarProdutoCommand>> Atualizar(AtualizarProdutoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirProdutoCommand>>> Excluir(ExcluirProdutoDto dtos, CancellationToken cancellationToken);
        Task<PaginacaoResponse<ProdutoFilterDto>> RetornarPaginacao(PaginacaoRequest paginacaoRequest);
        //Task<PaginacaoResponse<ProdutoOrdemFabricacaoFilterDto>> RetornarProdutoOrdemFabricacaoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<List<ProdutoOrdemFabricacaoFilterDto?>> RetornarProdutoPorVendaPaginacao(Guid idVenda);
        Task<ProdutoByIdDto?> RetornarPorId(Guid id);
        Task<FormularioResponse<AdicionarTipoProdutoCommand>> AdicionarTipoProduto(AdicionarTipoProdutoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarTipoProdutoCommand>> AtualizarTipoProduto(AtualizarTipoProdutoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirTipoProdutoCommand>>> Excluir(ExcluirTipoProdutoDto deleteTipoProdutoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarTipoProdutoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarTipoProdutoPorId(Guid id);
        Task<FormularioResponse<AdicionarGrupoCommand>> AdicionarGrupo(AdicionarGrupoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarGrupoCommand>> AtualizarGrupo(AtualizarGrupoRequestDto dto, CancellationToken cancellationToken);       
        Task<List<FormularioResponse<ExcluirGrupoCommand>>> Excluir(ExcluirGrupoDto deleteGrupoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarGrupoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarGrupoPorId(Guid id);
        Task<FormularioResponse<AdicionarCodigoImportacaoCommand>> AdicionarCodigoImportacao(AdicionarCodigoImportacaoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarCodigoImportacaoCommand>> AtualizarCodigoImportacao(AtualizarCodigoImportacaoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirCodigoImportacaoCommand>>> Excluir(ExcluirCodigoImportacaoDto deleteCodigoImportacaoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarCodigoImportacaoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarCodigoImportacaoPorId(Guid id);
        Task<FormularioResponse<AdicionarSetorCommand>> AdicionarSetor(AdicionarSetorRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarSetorCommand>> AtualizarSetor(AtualizarSetorRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirSetorCommand>>> Excluir(ExcluirSetorDto deleteSetorDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarSetorPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarSetorPorId(Guid id);
        Task<FormularioResponse<AdicionarRuaCommand>> AdicionarRua(AdicionarRuaRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarRuaCommand>> AtualizarRua(AtualizarRuaRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirRuaCommand>>> Excluir(ExcluirRuaDto deleteRuaDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarRuaPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarRuaPorId(Guid id);
        Task<FormularioResponse<AdicionarSubgrupoCommand>> AdicionarSubgrupo(AdicionarSubgrupoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarSubgrupoCommand>> AtualizarSubgrupo(AtualizarSubgrupoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirSubgrupoCommand>>> Excluir(ExcluirSubgrupoDto deleteSubgrupoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarSubgrupoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarSubgrupoPorId(Guid id);
        Task<FormularioResponse<AdicionarPrateleiraCommand>> AdicionarPrateleira(AdicionarPrateleiraRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarPrateleiraCommand>> AtualizarPrateleira(AtualizarPrateleiraRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirPrateleiraCommand>>> Excluir(ExcluirPrateleiraDto deletePrateleiraDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarPrateleiraPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarPrateleiraPorId(Guid id);
        Task<FormularioResponse<AdicionarNcmCommand>> AdicionarNcm(AdicionarNcmRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarNcmCommand>> AtualizarNcm(AtualizarNcmRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirNcmCommand>>> Excluir(ExcluirNcmDto deleteNcmDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<NcmByCodeDto>> RetornarNcmPaginacao(PaginacaoRequest paginacaoRequest);
        Task<List<NcmByProdutoDto?>> RetornarNcmPorProduto(Guid id);
        Task<NcmByCodeDto?> RetornarNcmPorId(Guid id);
        Task<FormularioResponse<AdicionarFamiliaCommand>> AdicionarFamilia(AdicionarFamiliaRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarFamiliaCommand>> AtualizarFamilia(AtualizarFamiliaRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirFamiliaCommand>>> Excluir(ExcluirFamiliaDto deleteFamiliaDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarFamiliaPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarFamiliaPorId(Guid id);        
        Task<FormularioResponse<AdicionarTipoPrecoCommand>> AdicionarTipoPreco(AdicionarTipoPrecoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarTipoPrecoCommand>> AtualizarTipoPreco(AtualizarTipoPrecoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirTipoPrecoCommand>>> Excluir(ExcluirTipoPrecoDto deleteTipoPrecoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarTipoPrecoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarTipoPrecoPorId(Guid id);
        Task<FormularioResponse<AdicionarSetorProdutoCommand>> AdicionarSetorProduto(AdicionarSetorProdutoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarSetorProdutoCommand>> AtualizarSetorProduto(AtualizarSetorProdutoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirSetorProdutoCommand>>> Excluir(ExcluirSetorProdutoDto deleteSetorProdutoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<SetorProdutoByCodeDto>> RetornarSetorProdutoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<SetorProdutoByCodeDto?> RetornarSetorProdutoPorId(Guid id);
        Task<List<SetorProdutoFilterDto?>> RetornarSetorProdutoPorCadastro(bool mostrarCadastro);
        Task<FormularioResponse<AdicionarOrigemMaterialCommand>> AdicionarOrigemMaterial(AdicionarOrigemMaterialRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarOrigemMaterialCommand>> AtualizarOrigemMaterial(AtualizarOrigemMaterialRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirOrigemMaterialCommand>>> Excluir(ExcluirOrigemMaterialDto deleteOrigemMaterialDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<PadraoIdDescricaoFilterDto>> RetornarOrigemMaterialPaginacao(PaginacaoRequest paginacaoRequest);
        Task<PadraoIdDescricaoFilterDto?> RetornarOrigemMaterialPorId(Guid id);
        Task<FormularioResponse<AdicionarUnidadeMedidaCommand>> AdicionarUnidadeMedida(AdicionarUnidadeMedidaRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarUnidadeMedidaCommand>> AtualizarUnidadeMedida(AtualizarUnidadeMedidaRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirUnidadeMedidaCommand>>> Excluir(ExcluirUnidadeMedidaDto deleteUnidadeMedidaDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<UnidadeMedidaByCodeDto>> RetornarUnidadeMedidaPaginacao(PaginacaoRequest paginacaoRequest);
        Task<UnidadeMedidaByCodeDto?> RetornarUnidadeMedidaPorId(Guid id);
        Task<FormularioResponse<AdicionarClasseReajusteCommand>> AdicionarClasseReajuste(AdicionarClasseReajusteRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarClasseReajusteCommand>> AtualizarClasseReajuste(AtualizarClasseReajusteRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirClasseReajusteCommand>>> ExcluirClasseReajuste(ExcluirClasseReajusteDto deleteClasseReajusteDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<ClasseReajusteByCodeDto>> RetornarClasseReajustePaginacao(PaginacaoRequest paginacaoRequest);
        Task<ClasseReajusteByCodeDto?> RetornarClasseReajustePorId(Guid id);
        Task<FormularioResponse<AdicionarDesgastePolimentoCommand>> AdicionarDesgastePolimento(AdicionarDesgastePolimentoRequestDto dtos, CancellationToken cancellationToken);
        Task<FormularioResponse<AtualizarDesgastePolimentoCommand>> AtualizarDesgastePolimento(AtualizarDesgastePolimentoRequestDto dto, CancellationToken cancellationToken);
        Task<List<FormularioResponse<ExcluirDesgastePolimentoCommand>>> ExcluirDesgastePolimento(ExcluirDesgastePolimentoDto deleteDesgastePolimentoDto, CancellationToken cancellationToken);
        Task<PaginacaoResponse<DesgastePolimentoFilterDto>> RetornarDesgastePolimentoPaginacao(PaginacaoRequest paginacaoRequest);
        Task<DesgastePolimentoByCodeDto?> RetornarDesgastePolimentoPorId(Guid id);
    }
}
