namespace Application.DTOs.Vendas.Relatorios
{
    public class OrcamentoPedidoImpressaoDto
    {
        public string pedido { get; set; }
        public string empresa_razao_social { get; set; }
        public string empresa_endereco { get; set; }
        public string empresa_cep_bairro { get; set; }
        public string empresa_cidade_uf { get; set; }
        public string empresa_telefone { get; set; }
        public string empresa_e_mail { get; set; }
        public string empresa_site { get; set; }
        public string nome { get; set; }
        public string cob_cli_Ender { get; set; }
        public string cob_cli_bairro { get; set; }
        public string cob_cli_cep_cid_est { get; set; }
        public string ie { get; set; }
        public string fat_cli_ender { get; set; }
        public string fat_cli_bairro { get; set; }
        public string fat_cli_cep_cid_est { get; set; }
        public string ent_cli_ender { get; set; }
        public string ent_cli_bairro { get; set; }
        public string ent_cli_cep_cid_est { get; set; }
        public string cli_e_mail { get; set; }
        public string cpf_cnpj { get; set; }
        public string contato { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string norma_abnt { get; set; }
        public string data_criacao { get; set; }
        public string hora_criacao { get; set; }
        public string data_atualizacao { get; set; }
        public string hora_atualizacao { get; set; }
        public string vendedor { get; set; }
        public string celular_vendedor { get; set; }
        public string email_vendedor { get; set; }
        public string cli_obra { get; set; }
        public string status { get; set; }
        public string release { get; set; }
        public string rascunho { get; set; }
        public string suprimir { get; set; }
        public string total_geral { get; set; }
        public Boolean sup_vendedor { get; set; }
        public string casas_decimais { get; set; }
        public string cod_item { get; set; }
        public string qtde { get; set; }
        public string um { get; set; }
        public string dsc_produto { get; set; }
        public string vlr_unit { get; set; }
        public string vlr_tot { get; set; }
        public string texto_cabecalho { get; set; }
        public Guid cod_empresa { get; set; }
        public string mensagem { get; set; }
        public string L001 { get; set; }
        public string L002 { get; set; }
        public string L003 { get; set; }
        public string L004 { get; set; }
        public string L005 { get; set; }
        public string L006 { get; set; }
        public string L007 { get; set; }
        public string L008 { get; set; }
        public string L009 { get; set; }
        public string L010 { get; set; }
        public string L011 { get; set; }
        public string L012 { get; set; }
        public string L013 { get; set; }
        public string L014 { get; set; }
        public string L015 { get; set; }
        public string L016 { get; set; }
        public string L017 { get; set; }
        public string L018 { get; set; }
        public string L019 { get; set; }
        public string L020 { get; set; }
        public string L021 { get; set; }
        public string L022 { get; set; }
        public string L023 { get; set; }
        public string L024 { get; set; }
        public string L025 { get; set; }
        public string L026 { get; set; }
        public string L027 { get; set; }
        public string L028 { get; set; }
        public string L029 { get; set; }
        public string L030 { get; set; }
        public string L031 { get; set; }
        public string L032 { get; set; }
        public string L033 { get; set; }
        public string L034 { get; set; }
        public string L035 { get; set; }
        public string L036 { get; set; }
        public string L037 { get; set; }
        public string L038 { get; set; }
        public string L039 { get; set; }
        public string L040 { get; set; }
        public string L041 { get; set; }
        public string L042 { get; set; }
        public string L043 { get; set; }
        public string L044 { get; set; }
        public string L045 { get; set; }
    }
}
